name: Android ARM (arm64+v7a)
on:
  workflow_dispatch:
  push:
    paths:
      - standalone/export_presets.cfg
      - .github/workflows/android-arm.yml

env:
  GODOT_REPOSITORY: nikitalita/godot
  GODOT_MAIN_SYNC_REF: gdre-wb-f964fa714f5
  SCONSFLAGS: verbose=yes warnings=all werror=no module_text_server_fb_enabled=yes minizip=yes deprecated=yes angle=yes accesskit=no
  SCONSFLAGS_TEMPLATE: disable_path_overrides=no no_editor_splash=yes module_camera_enabled=no module_mobile_vr_enabled=no module_upnp_enabled=no module_websocket_enabled=no module_csg_enabled=yes module_gridmap_enabled=yes use_static_cpp=yes builtin_freetype=yes builtin_libpng=yes builtin_zlib=yes builtin_libwebp=yes builtin_libvorbis=yes builtin_libogg=yes disable_3d=no
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  group: android-arm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux Editor (for export)
            os: ubuntu-22.04
            id: linux-editor
            platform: linux
            target: editor
            sconsflags: -j4 debug_symbols=no tests=yes
            rust-arch: x86_64-unknown-linux-gnu
            alt-rust-arch: none
            bin: ./bin/godot.linuxbsd.editor.x86_64

          - name: Android Template Release (arm64+v7a)
            os: ubuntu-22.04
            id: android-template
            platform: android
            target: template_release
            rust-arch: x86_64-linux-android
            alt-rust-arch: aarch64-linux-android
            sconsflags: -j4 production=yes debug_symbols=no optimize=size use_lto=yes generate_android_binaries=yes
            bin: ./bin/godot.linuxbsd.editor.x86_64

    steps:
      - name: checkout-godot
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GODOT_REPOSITORY }}
          ref: ${{ env.GODOT_MAIN_SYNC_REF }}

      - name: checkout-gdsdecomp
        uses: actions/checkout@v4
        with:
          path: modules/gdsdecomp
          fetch-depth: 0

      - name: copy actions
        shell: bash
        run: cp -R modules/gdsdecomp/.github/actions/* .github/actions/

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        id: restore-cache
        with:
          cache-name: ${{ matrix.id }}-${{ matrix.target }}
        continue-on-error: true

      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm clang-format libwayland-bin patchelf
      - name: Set up JDK 17
        if: matrix.platform == 'android'
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v4
      - name: Setup python and scons
        uses: ./.github/actions/godot-deps
      - name: Rust Add target
        shell: sh
        run: rustup target add ${{ matrix.rust-arch }}
      - name: Rust Add alt target
        if: matrix.alt-rust-arch != 'none'
        shell: sh
        run: rustup target add ${{ matrix.alt-rust-arch }}
      - name: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Download pre-built Android Swappy Frame Pacing Library
        if: matrix.platform == 'android'
        run: python ./misc/scripts/install_swappy_android.py

      - name: Compile Editor
        if: matrix.target == 'editor'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: editor

      - name: Compile godot export template arm32 (v7a)
        if: matrix.platform == 'android'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: -j4 arch=arm32 ${{ env.SCONSFLAGS }} ${{ env.SCONSFLAGS_TEMPLATE }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}

      - name: Compile godot export template arm64
        if: matrix.platform == 'android'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: -j4 arch=arm64 ${{ env.SCONSFLAGS }} ${{ env.SCONSFLAGS_TEMPLATE }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}

      - name: Compile godot export template x86_64 (linux only)
        if: matrix.platform == 'linux' && (matrix.target == 'template_release' || matrix.target == 'template_debug')
        uses: ./.github/actions/godot-build
        with:
          scons-flags: -j4 arch=x86_64 ${{ env.SCONSFLAGS }} ${{ env.SCONSFLAGS_TEMPLATE }} ${{ matrix.sconsflags }}
          platform: ${{ matrix.platform }}
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.id }}-${{ matrix.target }}
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: GDRE_tools-${{ matrix.target }}-${{ matrix.platform }}-arm
          path: ${{ github.workspace }}/bin/*
          retention-days: 90

  export:
    needs: build
    runs-on: ubuntu-24.04
    name: Android export APK
    steps:
      - name: checkout-gdsdecomp
        uses: actions/checkout@v4
        with:
          path: modules/gdsdecomp
          fetch-depth: 0
      - name: copy actions
        shell: bash
        run: |
          mkdir -p bin/
          mkdir -p .github/actions/
          cp -R modules/gdsdecomp/.github/actions/* .github/actions/
      - name: Download editor artifact
        uses: actions/download-artifact@v4
        with:
          name: GDRE_tools-editor-linux-arm
          path: bin
      - name: Download template artifact
        uses: actions/download-artifact@v4
        with:
          name: GDRE_tools-template_release-android-arm
          path: bin
      - name: set permissions
        shell: bash
        run: chmod a+x bin/godot*
      - name: Export standalone GDRE Tools APK
        shell: pwsh
        run: |
          cd ${{ github.workspace }}/modules/gdsdecomp/standalone
          pwsh -File ${{ github.workspace }}/modules/gdsdecomp/.scripts/export.ps1 "Android" -path ".export/gdre_tools.apk" --no-debug
      - uses: actions/upload-artifact@v4
        with:
          name: GDRE_tools-standalone-android-arm
          path: ${{ github.workspace }}/modules/gdsdecomp/standalone/.export/*
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 90
